# Form implementation generated from reading ui file 'salirWindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_salirwind(object):
    def setupUi(self, salirwind):
        salirwind.setObjectName("salirwind")
        salirwind.resize(287, 190)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/exclamation_warning_15590.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        salirwind.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(parent=salirwind)
        self.label.setGeometry(QtCore.QRect(40, 30, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnSalir = QtWidgets.QPushButton(parent=salirwind)
        self.btnSalir.setGeometry(QtCore.QRect(70, 110, 31, 31))
        self.btnSalir.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/tickcirclehd_106142.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnSalir.setIcon(icon1)
        self.btnSalir.setIconSize(QtCore.QSize(45, 45))
        self.btnSalir.setObjectName("btnSalir")
        self.btnCancelar = QtWidgets.QPushButton(parent=salirwind)
        self.btnCancelar.setGeometry(QtCore.QRect(170, 110, 31, 31))
        self.btnCancelar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/crosscircleregular_106260.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnCancelar.setIcon(icon2)
        self.btnCancelar.setIconSize(QtCore.QSize(45, 45))
        self.btnCancelar.setObjectName("btnCancelar")

        self.retranslateUi(salirwind)
        QtCore.QMetaObject.connectSlotsByName(salirwind)

    def retranslateUi(self, salirwind):
        _translate = QtCore.QCoreApplication.translate
        salirwind.setWindowTitle(_translate("salirwind", "Salir"))
        self.label.setText(_translate("salirwind", "¿Desea salir del aplicativo?"))
